da<-read.table("household_power_consumption.txt",sep=";",nrows=2880,skip=66637)
library(datasets)
datetime <- strptime(paste(da$V1,da$V2), format='%d/%m/%Y %H:%M:%S')
da2<-cbind(da,datetime)
png(file="plot4.png")
par(mfrow=c(2,2))
with(da2,plot(datetime,V3,type="l",xlab="",ylab="Global Active Power"))
with(da2,plot(datetime,V5,type="l",ylab="Voltage"))
with(da2,plot(datetime,V7,type="n",xlab="",ylab="Energy sub metering"))
legend("topright",lty=1,bty="n",col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
with(da,points(datetime,V7,type="l",col="black"))
with(da,points(datetime,V8,type="l",col="red"))
with(da,points(datetime,V9,type="l",col="blue"))
with(da2,plot(datetime,V4,type="l",ylab="Global_reactive_power"))
dev.off(3)